{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: db-user
      remoteRef:
        key: {{ .Values.externalSecrets.dbUserKey | default "test-db-user" }}
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecrets.dbPasswordKey | default "test-db-password" }}
    - secretKey: jwt-key
      remoteRef:
        key: {{ .Values.externalSecrets.jwtKeyKey | default "test-jwt-key" }}
{{- end }}
